### ISSUE TITLE
License information?

### ISSUE THREAD

**Issue by AngledLuffa** [zplizzi/tensorflow-fast-rcnn#11]
Do you have any license information that you want to share?

Thanks for developing this tool!

**Comment by zplizzi** [comment]
I'm not quite sure how to add a license to a fork of Tensorflow, but you're free to use any code that I wrote in any way you wish. If you need this more formally, let me know the best way I can do that.

**Comment by AngledLuffa** [comment]
I think that's sufficient for now.  Thanks!

**Comment by AngledLuffa** [comment]
I guess one idea that occurred to me would be to have the repo be separate from the TF repo, since it seems you are adding new files without changing any existing ones.  Or try to get it merged into TF, that would also handle any licensing questions.

Regardless, it's very useful.  Again, thanks for putting this out there.
