### ISSUE TITLE
So we have to write code to calculate the size of the rois?

### ISSUE THREAD

**Issue by menglin0320** [zplizzi/tensorflow-fast-rcnn#4]
Well in the original version of fast rcnn, roi pooling takes a spatial_scale scalar and resize the bounding box, but it seems like your code only take the resized boudning box. So if we want to use your code, we have to write code involve spatial_scale ourselves?

**Comment by zplizzi** [comment]
This is correct - in my code example, I did:

``` python
roi_scaling = 16
input_rois = (input_rois / roi_scaling).astype(np.int32)
```
